version: '3.7'

services:
  db:
    image: postgres:11
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}

  web:
    build: ./docker/php-fpm
    depends_on:
      - db
    volumes:
      - ./:/var/www/symfony:cached
      - ./var/logs/symfony:/var/www/symfony/var/logs:cached
      - ./docker/php-fpm/php-limit.ini:/usr/local/etc/php/conf.d/php-limit.ini
    ports:
      - 8095:80

  node:
    image: node:12-alpine
    command: sh -c "yarn install && yarn encore dev --watch"
    volumes:
      - .:/app:cached
    working_dir: /app

  composer:
    image: composer:latest
    command: install
    depends_on:
      - web
    volumes:
      - .:/app

  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - 8096:8025

  storage:
    image: minio/minio:latest
    ports:
      - '9091:9000'
    environment:
      - MINIO_ACCESS_KEY=${S3_KEY}
      - MINIO_SECRET_KEY=${S3_SECRET}
    volumes:
      - ./var/s3:/data
    command: 'server /data'

  hub:
    image: elgalu/selenium:3.141.59-p14
    volumes:
      - /dev/shm:/dev/shm
    privileged: true
    environment:
      - SELENIUM_HUB_HOST=hub
      - SELENIUM_HUB_PORT=4445
      - GRID=true
      - CHROME=false
      - FIREFOX=false
    depends_on:
      - web

  chrome:
    image: elgalu/selenium:3.141.59-p14
    depends_on:
      - hub
    volumes:
      - /dev/shm:/dev/shm
    privileged: true
    environment:
      - NOVNC=true
      - SELENIUM_HUB_HOST=hub
      - SELENIUM_HUB_PORT=4445
      - SELENIUM_NODE_HOST={{CONTAINER_IP}}
      - SCREEN_WIDTH=1300
      - SCREEN_HEIGHT=999
      - VIDEO=false
      - GRID=false
      - CHROME=true
      - FIREFOX=false
    ports:
      - 6080:26080
